additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
  - "--certificatesresolvers.cloudflare.acme.email={{ .Values.contactEmail }}"
  - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: token

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: traefik-acme-pvc

volumeMounts:
  - name: data
    mountPath: /data

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  path: /data

service:
  enabled: true
  type: ClusterIP

ingressRoute:
  dashboard:
    enabled: true
