cloudflared:
  secretName: cloudflared-tunnel

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.lan.acme.tlschallenge=true"
  - "--certificatesresolvers.lan.acme.email={{ .Values.contactEmail }}"
  - "--certificatesresolvers.lan.acme.storage=/data/acme.json"

extraInitContainers:
  - name: fix-acme-perms
    image: busybox:1.36.1
    command: ["sh", "-c", "touch /data/acme.json && chmod 600 /data/acme.json"]
    volumeMounts:
      - name: traefik-data
        mountPath: /data

extraVolumes:
  - name: cloudflared-tunnel
    secret:
      secretName: cloudflared-tunnel
  - name: traefik-data
    hostPath:
      path: /var/lib/traefik # gets overridden at runtime

extraVolumeMounts:
  - name: cloudflared-tunnel
    mountPath: /etc/cloudflared
    readOnly: true
  - name: traefik-data
    mountPath: /data

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

persistence:
  enabled: true
  name: traefik-acme-pvc
  accessMode: ReadWriteOnce
  size: 1Gi
  path: "/data"
  type: pvc
