publicDomain: yourdomain.tld
contactEmail: contact@yourdomain.tld
tunnelName: your-tunnel-name
cloudflared:
  secretName: cloudflared-tunnel

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.lan.acme.tlschallenge=true"
  - "--certificatesresolvers.lan.acme.email={{ .Values.contactEmail }}"
  - "--certificatesresolvers.lan.acme.storage=/data/acme.json"

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: traefik-acme-pvc

volumeMounts:
  - name: data
    mountPath: /data

extraVolumes:
  - name: cloudflared-tunnel
    secret:
      secretName: { { .Values.cloudflared.secretName } }

extraVolumeMounts:
  - name: cloudflared-tunnel
    mountPath: /etc/cloudflared
    readOnly: true

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["websecure"]
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

persistence:
  enabled: true
  name: traefik-acme-pvc
  accessMode: ReadWriteOnce
  size: 1Gi
  path: "/data"
  type: pvc
