name: Validate Infrastructure Code

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: YAML Lint
        run: |
          pip install yamllint
          yamllint .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init & Validate
        working-directory: terraform/cloudflare
        run: |
          terraform init
          terraform validate

      - name: Ansible Syntax Check
        working-directory: ansible
        run: |
          ansible-playbook --syntax-check playbooks/setup-local-volumes.yml
