name: Validate Infrastructure Code

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: YAML Lint
        run: |
          pip install yamllint
          yamllint .

      - name: Terraform Validate
        working-directory: terraform/cloudflare
        run: |
          terraform init
          terraform validate

      - name: Ansible Syntax Check
        working-directory: ansible
        run: |
          ansible-playbook --syntax-check playbooks/setup-local-volumes.yml
